spring:
  application:
    name: spring-boot-caches
  h2:
    console:
      enabled: true # h2 console 사용할지 여부 결정
      path: /h2-console # h2 console 접근 경로
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    #generate-ddl: true # DDL 생성 여부(Spring Data JPA의 설정)
    hibernate:
      ddl-auto: none # DDL 생성 전략(Hibernate의 설정)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect # Hibernate Dialect 설정
        format_sql: true # SQL 출력 포맷 설정
        show_sql: true # SQL 출력 여부
        hbm2ddl:
          auto: update

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        sql: DEBUG
      jpa: DEBUG
